import fs from "node:fs";
import path from "node:path";

const contractNames = [
  "InkLauncherRegistry",
  "TipJar",
  "Guestbook",
  "BuilderBadge",
  "SimpleERC20",
  "MiniEscrow",
  "USDCTipJar",
  "USDCMiniEscrow"
] as const;

const rootDir = path.resolve(__dirname, "../../..");
const artifactDir = path.resolve(__dirname, "../artifacts/contracts");
const outputDir = path.resolve(rootDir, "apps/web/src/generated");

fs.mkdirSync(outputDir, { recursive: true });

const exports: string[] = [
  "import type { Abi } from \"viem\";",
  "",
  "/* Autogenerated by packages/contracts/scripts/exportArtifacts.ts. */"
];

for (const name of contractNames) {
  const artifactPath = path.join(artifactDir, `${name}.sol`, `${name}.json`);
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const exportName = `${name.replace(/^USDC/, "Usdc").charAt(0).toLowerCase()}${name.replace(/^USDC/, "Usdc").slice(1)}Abi`;

  exports.push(
    `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as Abi;`
  );
}

fs.writeFileSync(path.join(outputDir, "contracts.ts"), `${exports.join("\n\n")}\n`);

const deploymentsPath = path.join(outputDir, "deployments.json");
if (!fs.existsSync(deploymentsPath)) {
  fs.writeFileSync(deploymentsPath, "{}\n");
}

console.log(`Exported ABIs to ${path.relative(rootDir, outputDir)}`);
